image: quay.io/giantswarm/fluentd-loki-plugin
imageTag: 9ee2ce8

resources:
  limits:
    cpu: 100m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 200Mi

loki:
  username:
  password:
  url: http://loki:3100

fluentdConfig: |
  <match fluent.**>
    type null
  </match>

  <source>
    @type tail
    path /var/log/apiserver/audit.log
    pos_file /var/log/fluentd-audit.log.pos
    time_format %Y-%m-%dT%H:%M:%S.%NZ
    tag audit.*
    format json
    read_from_head true
  </source>

  <filter kubernetes.**>
    type kubernetes_metadata
  </filter>

  <match audit.**>
    @type loki
    url "#{ENV['LOKI_URL']}"
    username "#{ENV['LOKI_USERNAME']}"
    password "#{ENV['LOKI_PASSWORD']}"
    extra_labels {"env":"dev"}
    flush_interval 10s
    flush_at_shutdown true
    buffer_chunk_limit 1m
  </match>