apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fluentd-loki.fullname" . }}
  labels:
    app: {{ template "fluentd-loki.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"

