apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fluentd-loki.fullname" . }}
  labels:
    app: {{ template "fluentd-loki.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  loki_password: {{if not .}}{{ .Values.loki.password | b64enc }}{{end}}
